notifications:
    email: false

sudo: false

jobs:
    include:
        -
            name: ShellCheck
            stage: ShellCheck
            language: sh
            before_install:
                - sudo apt update
                - sudo apt install --assume-yes shellcheck
            script:
                - shellcheck xdebug
                - shellcheck tests/tests.sh

        - &php-job
            name: PHP 7.2
            stage: Tests
            language: php
            php: 7.2
            before_install:
                - phpenv config-rm xdebug.ini
            script:
                - tests/tests.sh
        -
            <<: *php-job
            name: PHP 7.3
            php: 7.3
        -
            <<: *php-job
            name: PHP 7.4
            php: 7.4
        -
            name: Without PHP
            stage: Tests
            language: sh
            before_install:
                - PATH=$(echo $PATH | sed 's/:\/home\/travis\/.phpenv\/shims//')
                - if command -v php > /dev/null; then exit 1; fi
            script:
                - tests/tests.sh

